#! /bin/bash
#
# Installs just which is just a command runner


set -eu;

: "${JUST_VER:=1.33.0}"
: "${SRC_DIR:=/usr/local/src}"

echo "Installing just ${JUST_VER}...";
echo -ne '[                                                       ] (0%)\r';
mkdir -p "$SRC_DIR/just"
curl --proto =https --tlsv1.2 -sSfL https://github.com/casey/just/releases/download/1.33.0/just-1.33.0-x86_64-unknown-linux-musl.tar.gz |
tar --no-same-owner --no-same-permissions -C "$SRC_DIR/just" -xz
echo -ne '[###########################                            ] (50%)\r';
ln -s $SRC_DIR/just/just /usr/bin/just
echo -ne '[#######################################################] (100%)\r\n';
