#! /bin/bash
#
# Installs tmux plugin manager (tpm) if it is not already

set -eu;

: "${TPM_PATH:=~/.tmux/plugins/tpm}"


if [ ! -d $TPM_PATH ]; then
echo 'Installing tmux plugin manager...'
    git clone https://github.com/tmux-plugins/tpm $TPM_PATH
else
    echo 'Tpm seems to be already installed'
fi