FROM docker.io/fedora

ARG NVIM_VER=v0.9.5
ARG TMUX_PREFIX="C-b"

RUN update-ca-trust
# dnf --setopt=sslverify=0 -y update && \
RUN dnf --setopt=sslverify=0 -y install git \ 
    wget \
    tmux \
    ripgrep \
    gcc \
    lua;

WORKDIR /tmp

RUN set -eu && \
    echo "Installing nvim..." && \
    wget -q https://github.com/neovim/neovim/releases/download/${NVIM_VER}/nvim-linux64.tar.gz && \
    tar --no-same-owner --no-same-permissions -xf nvim-linux64.tar.gz && \
    cp -r nvim-linux64 /usr/local/src/nvim-linux64 && \
    ln -s /usr/local/src/nvim-linux64/bin/nvim /usr/bin/nvim && \
    rm -rf nvim-*;
#RUN chmod +x /usr/share/src/nvim-linux64/bin/nvim

WORKDIR /tmp/nvim-385

COPY ./scripts ./scripts
COPY ./nvim ./nvim
COPY ./tmux ./tmux
COPY ./install.zsh ./install.zsh

WORKDIR /tmp

# install just
RUN mkdir -p ~/bin && \
    wget -qO- https://just.systems/install.sh | bash -s -- --to ~/bin && \
    export PATH="$PATH:$HOME/bin"


RUN set -e && \
    echo "CloningInstalling nvim-385 preset..." && \
    chmod +x ./nvim-385/install.zsh && \
    source /tmp/nvim-385/install.zsh;



#CMD ["zsh", "/tmp/nvim-385/configure-tmux.zsh"]
COPY ./docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

WORKDIR /root/.config/nvim
ENTRYPOINT ["/docker-entrypoint.sh"]

