version: '3.8'
services: 
  nvim-385: 
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: nvim-385
    container_name: nvim-385
  nvim-385-test: 
    build: 
      context: .
      dockerfile: ./Dockerfile.test
    image: nvim-385-test
    container_name: nvim-385-test
