return {
    --base = "#0A0A0C",    -- Very dark gray-blue for depth
    --mantle = "#101013",  -- Slightly muted dark gray with blue undertones
    --crust = "#131315",   -- A neutral dark gray for separation
    --base = "#090A0B", -- Cool dark neutral
    --mantle = "#121314", -- Slightly brighter neutral
    --crust = "#161718", -- Subtle depth for borders and UI elements
    base = "#121314", -- Light neutral dark, significantly brighter than before
    mantle = "#1A1B1C", -- Midway between #121314 and #252627
    crust = "#1F2021", -- Midway between #161718 and #2A2B2C
    statusline = "#5C5C5C",
    statusline_icons = "#525252",
    --base = "#0C0C0A",    -- Very dark brown-gray
    --mantle = "#131310",  -- Muted warm dark gray
    --crust = "#1A1A17",
    rosewater = "#f4d3da",
    --mauve = "#c9b7e6",
    --red = "#e06c75",
    --red = "#d78787",
    red = "#e5788f",
    --red = "#d2686e",
    --red = "#c85c6c",
    --red = "#b4585b",
    lavender = "#d3d7df", -- Slightly lighter, to balance blue
    peach = "#f2b18e", -- Softer peach, closer to the muted theme
    yellow = "#f0c674", -- Pastel yellow, less harsh
    teal = "#15baba", -- Reduce saturation to harmonize with sky
    --blue = "#61afef",     -- Keep as is (good for accents)
    --blue =  "#6db9f8",
    --green = "#a3be8c",    -- Slightly softer, more natural green
    green = "#9ecb8c",
    --maroon = "#d84755",   -- Deeper tone for better distinction from red
    sky = "#89dceb", -- Slightly lighter to feel airier
    pink = "#f5c2e7", -- Keep as is (delicate and consistent)
    sapphire = "#68aee8" -- Slightly darker and cooler for distinction
}
